version: '3'
services:
  front:
    container_name: my-glare-glassmorphism-with-tilt-effect
    build: .
    ports:
      - 3001:3000
    volumes:
      - type: volume
        source: node-modules
        target: /app/node_modules
      - type: bind
        source: .
        target: /app
    working_dir: /app

volumes:
  node-modules:
